verifier.originalClientId=localhost
verifier.clientIdPrefix=x509_san_dns
verifier.jar.signing.algorithm=ES256
verifier.requestJwt.requestUriMethod=Post
verifier.allowedRedirectUriSchemes=http,https
verifier.publicUrl=http://localhost:8080
